In [1]:
import numpy as np

In [2]:
# Step 1 Collect Data
x = np.array([[0,0,1],
            [0,1,1],
            [1,0,1],
            [1,1,1]])
                
y = np.array([[0],
            [1],
            [1],
            [0]])


In [3]:
#print x

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]


In [4]:
#print y 

[[0]
 [1]
 [1]
 [0]]


In [5]:
#Step 2 build model

num_epochs = 1

#initialize weights
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

In [6]:
#print syn0

[[-0.00896954  0.63051633  0.97238696  0.2205912 ]
 [ 0.80236435 -0.88821416  0.71289103  0.52543106]
 [ 0.27429976 -0.29205953  0.57121292  0.69364235]]


In [7]:
#print syn1

[[ 0.30339426]
 [-0.45778467]
 [ 0.09523754]
 [-0.34639674]]


In [8]:
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)

    return 1/(1+np.exp(-x))

In [27]:
#Step 3 Train Model

for j in xrange(num_epochs):
    #feed forward through layers 0,1, and 2
    k0 = x
    k1 = nonlin(np.dot(k0, syn0))
    #print "k1 and weight multiplication "
    #print k0, syn0
    #print "input layer  k "
    #print k1
    k2 = nonlin(np.dot(k1, syn1))
    #print "syn1"
    #print syn1
    #print "input layer k2"
    #print k2
    #how much did we miss the target value?
    k2_error = y - k2
    
    #print "actual output"
    #print y
    #print "code output"
    #print k2
    #print "error in praposgation "
    #print k2_error   
    
    if (j% 10000) == 0:
        print "Error:" + str(np.mean(np.abs(k2_error)))
        print "output:" +str(k2)
        print "actual out:"+str(y)
    #in what direction is the target value?
    k2_delta = k2_error*nonlin(k2, deriv=True)
    #print "k2_delta in error field"
    #print k2
    #print "dervatinve of k2"
    #print nonlin(k2, deriv=True)
    #print "k2 delta is k2.deriavtiver of k2"
    #print k2_delta    
    #how much did each k1 value contribute to k2 error
    k1_error = k2_delta.dot(syn1.T)
    #print "k1_error"
    #print k1    
    k1_delta= k1_error * nonlin(k1,deriv=True)    
    syn1 =syn1+ k1.T.dot(k2_delta)
    syn0 =syn0+ k0.T.dot(k1_delta)
    

Error:0.00220473771534
output:[[ 0.00110849]
 [ 0.99800735]
 [ 0.99719055]
 [ 0.00290835]]
actual out:[[0]
 [1]
 [1]
 [0]]
Error:0.00214379759673
output:[[ 0.00107472]
 [ 0.99806361]
 [ 0.99726552]
 [ 0.0028296 ]]
actual out:[[0]
 [1]
 [1]
 [0]]
Error:0.00208756564488
output:[[ 0.00104365]
 [ 0.99811548]
 [ 0.99733479]
 [ 0.00275688]]
actual out:[[0]
 [1]
 [1]
 [0]]
Error:0.0020354676815
output:[[ 0.00101495]
 [ 0.9981635 ]
 [ 0.99739903]
 [ 0.00268946]]
actual out:[[0]
 [1]
 [1]
 [0]]
Error:0.00198702283152
output:[[  9.88326538e-04]
 [  9.98208133e-01]
 [  9.97458839e-01]
 [  2.62673662e-03]]
actual out:[[0]
 [1]
 [1]
 [0]]
Error:0.00194182491289
output:[[  9.63553724e-04]
 [  9.98249742e-01]
 [  9.97514694e-01]
 [  2.56818236e-03]]
actual out:[[0]
 [1]
 [1]
 [0]]
